Repository Dariaengin/Sharlink, pull requests merged in 2025-05, with the labels that each got.

#17 Backend side and db
  backend/.gitignore
  backend/auth/auth.js
  backend/config/apiRoutes.js
  backend/config/mongoose.js
  backend/controller/userController.js
  backend/index.js
  backend/models/collectionModel.js
  backend/models/commentModel.js
  backend/models/linkModel.js
  backend/models/userModel.js
  backend/package-lock.json
  backend/package.json
  backend/server.js
Labels: enhancement

#16 profile page
  .gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/collection/AddLinkForm.jsx
  frontend/src/components/comment/AddCommentForm.jsx
  frontend/src/components/comment/CommentItem.jsx
  frontend/src/components/common/Button.jsx
  frontend/src/components/common/Header.jsx
  frontend/src/components/common/Loader.jsx
  frontend/src/components/link/CommentList.jsx
  frontend/src/components/link/LinkDetail.jsx
  frontend/src/components/profile/CollectionList.jsx
  frontend/src/components/profile/UserInfo.jsx
  frontend/src/pages/CollectionPage.jsx
  frontend/src/pages/CollectionsListPage.jsx
  frontend/src/pages/Homepage.jsx
  frontend/src/pages/Profile.jsx
  frontend/src/pages/ProfilePage.jsx
Labels: enhancement

#22 Homepage with db
  backend/config/apiRoutes.js
  backend/controller/collectionController.js
  backend/server.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/images/Best-Podcasts-Right-Now-cover.jpg
  frontend/public/images/Cozy-Bookstores-cover.jpg
  frontend/public/images/Dream-Travel-Destinations-cover.jpg
  frontend/public/images/Favorite-Coffee-Spots-cover.jpg
  frontend/public/images/Frontend-Tools-cover.jpg
  frontend/public/images/Hidden-Gem-Restaurants-cover.jpg
  frontend/public/images/Home-Decor-Inspo-cover.jpeg
  frontend/public/images/Inspiring-Musicians-cover.jpg
  frontend/public/images/JavaScript-Resources-cover.png
  frontend/public/images/Local-Art-Museums-cover.jpg
  frontend/public/images/Must-See-Movies-cover.jpg
  frontend/public/images/Weekend-Getaways-cover.jpg
  frontend/src/App.jsx
  frontend/src/components/collection/CollectionCard.jsx
  frontend/src/components/collection/LinkCard.jsx
  frontend/src/components/collection/LinkList.jsx
  frontend/src/components/collection/TopCollections.jsx
  frontend/src/components/collection/TopLinks.jsx
  frontend/src/pages/Homepage.jsx
  frontend/src/pages/LinkPage.jsx
  frontend/src/pages/OneCollectionPage.jsx
Labels: enhancement

#31 Homepage with db
  backend/config/apiRoutes.js
  backend/controller/userController.js
  backend/middlewares/ownership.js
  backend/server.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/auth/LoginForm.jsx
  frontend/src/components/auth/SignUpForm.jsx
  frontend/src/components/auth/common/Button.jsx
  frontend/src/components/auth/common/input.jsx
  frontend/src/context/AuthContext.jsx
  frontend/src/pages/Homepage.jsx
  frontend/src/pages/LinkPage.jsx
  frontend/src/pages/LoginPage.jsx
  frontend/src/pages/OneCollectionPage.jsx
  frontend/src/pages/SignUpPage.jsx
Labels: enhancement

#36 User profile
  frontend/src/components/auth/AuthContext.jsx
  frontend/src/components/auth/LoginForm.jsx
  frontend/src/components/common/Header.jsx
  frontend/src/components/profile/UserInfo.jsx
  frontend/src/main.jsx
  frontend/src/pages/ProfilePage.jsx
Labels: enhancement

#38 Add link and edit link
  backend/auth/auth.js
  backend/controller/linkController.js
  backend/package.json
  backend/server.js
  frontend/src/components/collection/AddLinkForm.jsx
  frontend/src/components/collection/EditLinkForm.jsx
Labels: enhancement

#43 updated collection with linkIds when adding new link
  backend/controller/linkController.js
  backend/models/linkModel.js
Labels: bug

#42 save link inside collection
  frontend/src/components/collection/AddLinkForm.jsx
Labels: enhancement

#45 Refine backend side with validation and error messages
  backend/controller/linkController.js
  backend/models/linkModel.js
  backend/server.js
Labels: bug, enhancement

#40 Add AI model for our project
  backend/config/apiRoutes.js
  backend/package-lock.json
  backend/package.json
  backend/routes/aiSearch.js
  frontend/src/App.jsx
  frontend/src/components/common/Header.jsx
  frontend/src/pages/AISearch.jsx
Labels: enhancement

#34 search bar #27
  backend/controller/collectionController.js
  frontend/src/components/collection/TopCollections.jsx
  frontend/src/components/common/SearchBar.jsx
  frontend/src/pages/Homepage.jsx
Labels: enhancement
